### ISSUE TITLE
本番環境下でLet's encryptが取得できてない

### ISSUE THREAD

**Issue by ryota-nakano** [steamships/bagisto-docker#2]
docker-compose.yml
```yml
services:
  https-portal:
    environment:
      STAGE:production
```

としたときに、上手く動かない。回数制限に引っかかっているのかもしれない説が濃厚。
